name: Login na API e Armazenar Token

on:
  push:
    branches:
      - master

jobs:
  login_and_store_token:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar c칩digo
      uses: actions/checkout@v2

    - name: Instalar jq
      run: |
        sudo apt-get update -y
        sudo apt-get install jq -y

    - name: Fazer login na API e armazenar token
      env:
        API_EMAIL: ${{ secrets.API_EMAIL }}
        API_PASSWORD: ${{ secrets.API_PASSWORD }}
      run: |
        # Faz o login na API usando as vari치veis de ambiente API_EMAIL e API_PASSWORD
        response=$(curl -X 'POST' 'https://auth.development.xguardianplatform.io/login' \
          -H 'accept: application/json' \
          -H 'Content-Type: application/json' \
          -d '{
            "email": "'"${API_EMAIL}"'",
            "password": "'"${API_PASSWORD}"'"
          }' | jq -r '.token')

        # Armazena o token como um segredo no GitHub Actions
        echo -n "$response" | gh secret set API_TOKEN

        # Limpa a vari치vel tempor치ria que continha o token
        unset response
