name: Login na API e Armazenar Token

on:
  push:
    branches:
      - master

jobs:
  login_and_store_token:
    runs-on: ubuntu-latest

    env:
      API_EMAIL: ${{ secrets.API_EMAIL }}
      API_PASSWORD: ${{ secrets.API_PASSWORD }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Verificar código
      uses: actions/checkout@v2

    - name: Instalar GitHub CLI
      run: |
        # Instalação do GitHub CLI usando o repositório de pacotes genéricos
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo sh -c 'echo "deb [arch=amd64] https://cli.github.com/packages stable main" > /etc/apt/sources.list.d/github-cli.list'
        sudo apt-get update
        sudo apt-get install gh -y

    - name: Fazer login no GitHub CLI
      run: gh auth login --with-token <<<"${GH_TOKEN}"

    - name: Fazer login na API e armazenar token
      run: |
        # Faz o login na API usando as variáveis de ambiente API_EMAIL e API_PASSWORD
        response=$(curl -X 'POST' 'https://auth.development.xguardianplatform.io/login' \
          -H 'accept: application/json' \
          -H 'Content-Type: application/json' \
          -d '{
            "email": "'"${API_EMAIL}"'",
            "password": "'"${API_PASSWORD}"'"
          }' | jq -r '.token')

        # Armazena o token como um segredo no GitHub Actions usando echo e gh
        echo -n "$response" | gh secret set API_TOKEN -

        # Limpa a variável temporária que continha o token
        unset response
